import '@angular/compiler';
import {Component,provideZonelessChangeDetection,ChangeDetectorRef,inject} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {FormsModule} from '@angular/forms';
import './style.css';

type User={name:string;email:string;role:string};
type Finding={id:number;reference:string;cve:string|null;asset:string;zone:string;product:string;product_version:string;status:string;treatment:string;input:any;calculation:any;cti:any;revision_id:number};
class PrimeApp {
 private cdr=inject(ChangeDetectorRef);
 user:User|null=null; email=''; password=''; code=''; csrf=''; mfa:any=null; recovery:string[]=[];
 error=''; notice=''; busy=false; findings:Finding[]=[]; policy=''; query=''; zone=''; status='';
 selected:Finding|null=null; history:any=null; treatment=''; reviewNote=''; events:any[]=[]; view='hallazgos';
 async ngOnInit(){try{const s=await this.api('/session');this.user=s.user;if(this.user)await this.load();}catch(e){this.handle(e);}finally{this.cdr.detectChanges();}}
 get canWrite(){return this.user?.role==='analista'||this.user?.role==='administrador';}
 get zones(){return [...new Set(this.findings.map(x=>x.zone))];}
 get filtered(){const q=this.query.toLowerCase();return this.findings.filter(f=>(!this.zone||f.zone===this.zone)&&(!this.status||f.status===this.status)&&(!q||[f.reference,f.cve,f.asset,f.product].join(' ').toLowerCase().includes(q)));}
 get urgent(){return this.findings.filter(f=>f.calculation.kev_urgent).length;}
 get pending(){return this.findings.filter(f=>f.calculation.provisional).length;}
 get closed(){return this.findings.filter(f=>f.status==='mitigado').length;}
 handle(e:unknown){this.error=e instanceof Error?e.message:String(e);}
 async api(path:string,method='GET',body?:unknown):Promise<any>{
  const form=body instanceof FormData;
  const headers:Record<string,string>={'Accept':'application/json'};
  if(method!=='GET'){headers['X-CSRF-TOKEN']=this.csrf;if(!form)headers['Content-Type']='application/json';}
  const r=await fetch('/api'+path,{method,credentials:'same-origin',headers,body:method==='GET'?undefined:(form?body as FormData:JSON.stringify(body??{}))});
  const data=await r.json().catch(()=>({message:'Respuesta inesperada del servidor.'}));
  if(data.csrf)this.csrf=data.csrf;
  if(!r.ok){if(r.status===401){this.user=null;this.selected=null;this.mfa=null;}throw new Error(data.errors?Object.values(data.errors).flat().join(' '):(data.message||'La operación no pudo completarse.'));}
  return data;
 }
 async task(fn:()=>Promise<void>){this.busy=true;this.error='';this.notice='';try{await fn();}catch(e){this.handle(e);}finally{this.busy=false;this.cdr.detectChanges();}}
 async login(){await this.task(async()=>{this.mfa=await this.api('/auth/login','POST',{email:this.email,password:this.password});this.password='';});}
 async verify(){await this.task(async()=>{const x=await this.api('/auth/mfa','POST',{code:this.code});this.user=x.user;this.recovery=x.recovery_codes;this.code='';this.mfa=null;await this.load();});}
 async logout(){await this.task(async()=>{await this.api('/auth/logout','POST');this.user=null;this.findings=[];this.recovery=[];this.selected=null;});}
 async load(){const x=await this.api('/findings');this.findings=x.findings;this.policy=x.policy;if(this.selected)this.selected=this.findings.find(f=>f.id===this.selected!.id)??null;}
 async upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;await this.task(async()=>{const body=new FormData();body.append('file',file);const x=await this.api('/imports','POST',body);this.notice=`Lote ${x.batch_id}: ${x.count} hallazgos importados. Los CVE están pendientes de consulta CTI.`;await this.load();});(event.target as HTMLInputElement).value='';}
 async select(f:Finding){await this.task(async()=>{this.selected=f;this.treatment=f.treatment??'';this.reviewNote='';this.history=await this.api(`/findings/${f.id}/history`);});}
 async enrich(){if(!this.selected)return;await this.task(async()=>{const x=await this.api(`/findings/${this.selected!.id}/cti`,'POST');this.notice=`Consulta registrada. EPSS: ${this.ctiStatus(x.epss_status)}. KEV: ${this.ctiStatus(x.kev_status)}.`;await this.load();this.history=await this.api(`/findings/${this.selected!.id}/history`);});}
 async propose(){if(!this.selected)return;await this.task(async()=>{await this.api(`/findings/${this.selected!.id}/propose`,'POST',{treatment:this.treatment});this.notice='Propuesta registrada. Otra persona con rol Administrador debe revisar la evidencia.';await this.load();});}
 async attach(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||!this.selected)return;await this.task(async()=>{const body=new FormData();body.append('file',file);await this.api(`/findings/${this.selected!.id}/evidence`,'POST',body);this.history=await this.api(`/findings/${this.selected!.id}/history`);this.notice='Evidencia almacenada con huella SHA256.';});(event.target as HTMLInputElement).value='';}
 async review(){if(!this.selected)return;await this.task(async()=>{const x=await this.api(`/findings/${this.selected!.id}/review`,'POST',{note:this.reviewNote});this.notice=x.message;await this.load();});}
 async audit(){await this.task(async()=>{const x=await this.api('/audit');this.events=x.events;this.view='actividad';});}
 ctiStatus(s:string){return ({ok:'Disponible',pending:'Pendiente',error:'Error de consulta',missing:'Sin dato',not_applicable:'No aplica'} as Record<string,string>)[s]??s;}
 date(s:string){return new Date(s).toLocaleString('es-SV',{timeZone:'America/El_Salvador'});}
}
Component({selector:'prime-app',standalone:true,imports:[FormsModule],template:`
@if (!user) {
 <div class="login-layout"><section class="login-story"><div class="brand"><b class="mark">P</b> PRIME</div><span class="eyebrow">GESTIÓN DE VULNERABILIDADES</span><h1>Convierte hallazgos<br>en decisiones.</h1><p>Prioriza con contexto, conserva la trazabilidad y documenta cada tratamiento.</p><div class="story-bottom">PROTOTIPO ACADÉMICO · APEX ES UN ESCENARIO FICTICIO</div></section>
 <main class="login-main"><div class="login-card"><span class="eyebrow">ACCESO AL ESPACIO DE TRABAJO</span><h2>{{mfa ? 'Verifica tu identidad' : 'Bienvenido a PRIME'}}</h2><p class="muted">{{mfa ? 'Introduce el código de tu aplicación autenticadora o un código de recuperación.' : 'Ingresa con la cuenta local asignada a tu rol.'}}</p>
 @if(error){<p class="alert error" role="alert">{{error}}</p>}
 @if(!mfa){<form (ngSubmit)="login()"><label>Correo<input type="email" name="email" [(ngModel)]="email" required autocomplete="username"></label><label>Contraseña<input type="password" name="password" [(ngModel)]="password" required autocomplete="current-password"></label><button class="primary full" [disabled]="busy">{{busy?'Ingresando…':'Continuar'}}</button></form>}
 @else { @if(mfa.enrollment){<div class="enrollment"><strong>Configura tu segundo factor</strong><p>Añade una cuenta TOTP de 6 dígitos y 30 segundos en tu autenticador. Copia esta clave; se mostrará hasta confirmar el enrolamiento.</p><code>{{mfa.secret}}</code></div>}<form (ngSubmit)="verify()"><label>Código TOTP o de recuperación<input name="code" [(ngModel)]="code" required autocomplete="one-time-code"></label><button class="primary full" [disabled]="busy">{{busy?'Validando…':'Verificar y entrar'}}</button></form>}
 <p class="login-foot">Primera versión experimental. Los resultados académicos requieren validación independiente.</p></div></main></div>
} @else {
 <aside class="sidebar"><div class="brand"><b class="mark">P</b> PRIME</div><div class="workspace">Apex · Laboratorio<span>Espacio académico</span></div><span class="nav-label">ESPACIO DE TRABAJO</span><button aria-label="Hallazgos" [class.active]="view==='hallazgos'" (click)="view='hallazgos'">▤ <span>Hallazgos</span><small>{{findings.length}}</small></button>@if(user.role!=='analista'){<button aria-label="Actividad" [class.active]="view==='actividad'" (click)="audit()">◷ <span>Actividad</span></button>}<a href="/ejemplo25.csv" download>↓ <span>CSV de demostración</span></a><div class="sidebar-bottom"><span class="online"></span> Entorno local<div class="avatar-row"><b>{{user.name.charAt(0)}}</b><div>{{user.name}}<small>{{user.role}}</small></div></div><button (click)="logout()" [disabled]="busy">Cerrar sesión</button></div></aside>
 <main class="main"><header class="topbar"><span>Espacio de trabajo / <b>{{view==='hallazgos'?'Triaje contextual':'Actividad'}}</b></span><span class="badge">Prototipo 0.1</span></header><section class="content"><div class="page-heading"><div><span class="eyebrow">PLATAFORMA DE TRIAJE</span><h1>{{view==='hallazgos'?'Hallazgos y prioridades':'Registro de actividad'}}</h1><p class="muted">{{view==='hallazgos'?'Decisiones explicables, datos CTI con fecha y tratamiento documentado.':'Eventos de autenticación, importación, CTI y revisión.'}}</p></div>@if(view==='hallazgos'){<div class="actions"><a class="button secondary" href="/api/export">Exportar CSV</a>@if(canWrite){<label class="button primary upload">＋ Importar CSV<input type="file" accept=".csv" (change)="upload($event)" [disabled]="busy"></label>}</div>}</div>
 @if(error){<p class="alert error" role="alert">{{error}}</p>}@if(notice){<p class="alert notice" role="status">{{notice}}</p>}@if(busy){<p class="muted" role="status">Procesando…</p>}
 @if(recovery.length){<div class="recovery"><h3>Guarda tus códigos de recuperación</h3><p>Cada código puede usarse una sola vez. Guarda una copia privada antes de cerrar este aviso.</p><div class="code-grid">@for(c of recovery;track c){<code>{{c}}</code>}</div><button class="secondary" (click)="recovery=[]">Ya guardé mis códigos</button></div>}
 @if(view==='hallazgos'){
 <div class="metrics"><article><span>Hallazgos registrados</span><strong>{{findings.length}}</strong><small>En este espacio de trabajo</small></article><article><span>Atención urgente KEV</span><strong class="orange">{{urgent}}</strong><small>Explotación conocida del CVE</small></article><article><span>CTI pendiente o incompleta</span><strong>{{pending}}</strong><small>Decisiones provisionales</small></article><article><span>Tratamientos revisados</span><strong class="green">{{closed}}</strong><small>Cierres administrativos</small></article></div>
 <div class="experiment"><b>Política experimental</b><span>CVSS declarado + DREAD ponderado + EPSS. KEV establece atención urgente. La fórmula aún requiere evaluación independiente.</span></div>
 <section class="table-card"><div class="table-toolbar"><h2>Cola de tratamiento <span>{{filtered.length}}</span></h2><div class="filters"><input aria-label="Buscar hallazgo" placeholder="Buscar ID, CVE o activo…" [(ngModel)]="query"><select aria-label="Filtrar zona" [(ngModel)]="zone"><option value="">Todas las zonas</option>@for(z of zones;track z){<option [value]="z">{{z}}</option>}</select><select aria-label="Filtrar estado" [(ngModel)]="status"><option value="">Todos los estados</option><option value="abierto">Abierto</option><option value="propuesto">Propuesto</option><option value="mitigado">Mitigado</option></select></div></div>
 <div class="table-scroll"><table><thead><tr><th>HALLAZGO / CVE</th><th>ACTIVO Y ZONA</th><th>CVSS</th><th>IRC</th><th>PRIORIDAD</th><th>ESTADO</th><th></th></tr></thead><tbody>@for(f of filtered;track f.id){<tr><td><b>{{f.reference}}</b><small>{{f.cve || 'Configuración · sin CVE'}}</small></td><td>{{f.asset}}<small>{{f.zone}}</small></td><td>{{f.input.cvss}}</td><td><b>{{f.calculation.display_score}}</b>@if(f.calculation.provisional){<small class="orange">Provisional</small>}</td><td><span class="pill" [class.critical]="f.calculation.kev_urgent || f.calculation.severity==='Crítico'" [class.high]="f.calculation.severity==='Alto'">{{f.calculation.priority}}</span></td><td><span class="status">{{f.status}}</span></td><td><button class="detail-button" (click)="select(f)" [disabled]="busy">Ver detalle →</button></td></tr>}@empty{<tr><td colspan="7"><div class="empty"><h3>{{findings.length?'Sin coincidencias':'Comienza con tus hallazgos'}}</h3><p>{{findings.length?'Cambia la búsqueda o los filtros.':'Descarga el CSV de demostración e impórtalo para explorar el flujo. Sus datos son sintéticos y no constituyen resultados de investigación.'}}</p></div></td></tr>}</tbody></table></div><footer class="table-footer">{{policy}} · Orden: atención KEV, IRC e ID estable. La pertenencia a KEV no demuestra compromiso del activo.</footer></section>
 } @else {<section class="table-card"><div class="table-scroll"><table><thead><tr><th>FECHA</th><th>EVENTO</th><th>USUARIO</th><th>DETALLE</th></tr></thead><tbody>@for(e of events;track e.id){<tr><td>{{date(e.created_at)}}</td><td>{{e.event}}</td><td>{{e.user_id || 'Sin sesión'}}</td><td>{{e.details}}</td></tr>}</tbody></table></div></section>}
 <p class="page-foot">PRIME · Investigación aplicada · Defensa prevista para el 1 de diciembre de 2026</p></section></main>
 @if(selected){<div class="drawer-shade" (click)="selected=null"></div><aside class="drawer"><div class="drawer-heading"><div><span class="eyebrow">DETALLE DEL HALLAZGO</span><h2>{{selected.reference}}</h2></div><button aria-label="Cerrar detalle" class="close" (click)="selected=null">×</button></div><p class="muted">{{selected.cve || 'Sin CVE asociado'}} · {{selected.asset}}</p><div class="detail-score"><strong>{{selected.calculation.display_score}}</strong><div>{{selected.calculation.priority}}<small>{{selected.calculation.provisional?'CTI incompleta · decisión provisional':'Datos CTI registrados o no aplicables'}}</small></div></div>
 <h3>Contexto y fundamento</h3><dl><dt>Producto</dt><dd>{{selected.product}} {{selected.product_version}}</dd><dt>Zona</dt><dd>{{selected.zone}}</dd><dt>CVSS declarado</dt><dd>{{selected.input.cvss}} · v{{selected.input.cvss_version}}</dd><dt>DREAD ponderado</dt><dd>{{selected.calculation.dread.toFixed(3)}}</dd><dt>Base combinada</dt><dd>{{selected.calculation.base.toFixed(3)}}</dd></dl><p class="context-text">{{selected.input.justification}}</p><details><summary>Vector y dimensiones</summary><code class="vector">{{selected.input.cvss_vector}}</code><p>D: {{selected.input.damage}} · E: {{selected.input.exploitability}} · R: {{selected.input.reproducibility}} · A: {{selected.input.affected_users}} · Ds: {{selected.input.discoverability}}</p></details>
 <h3>Inteligencia de amenazas</h3><dl><dt>EPSS</dt><dd>{{ctiStatus(selected.cti.epss.status)}}{{selected.cti.epss.value!==null && selected.cti.epss.value!==undefined?' · '+selected.cti.epss.value:''}}</dd><dt>Percentil</dt><dd>{{selected.cti.epss.percentile ?? 'No disponible'}}</dd><dt>Fecha EPSS</dt><dd>{{selected.cti.epss.data_date || 'No disponible'}}</dd><dt>KEV</dt><dd>{{ctiStatus(selected.cti.kev.status)}}{{selected.cti.kev.value===true?' · Presente':selected.cti.kev.value===false?' · Ausente':''}}</dd><dt>Consulta</dt><dd>{{date(selected.cti.queried_at)}}</dd></dl>@if(canWrite && selected.cve){<button class="secondary" (click)="enrich()" [disabled]="busy">Consultar CTI y crear revisión</button>}
 <h3>Tratamiento</h3><p class="muted">Estado: {{selected.status}}. Un cierre registrado requiere revisión humana de la evidencia; no cambia automáticamente el riesgo residual.</p>@if(canWrite && selected.status==='abierto'){<label>Propuesta<textarea rows="3" [(ngModel)]="treatment" placeholder="Control, alcance, compatibilidad y prueba de verificación…"></textarea></label><button class="primary" (click)="propose()" [disabled]="busy || !treatment">Registrar propuesta</button>}@else{<p>{{selected.treatment || 'Sin propuesta'}}</p>}
 <h3>Evidencias</h3>@if(canWrite){<label class="button secondary upload">Adjuntar TXT, JSON, PNG o PDF<input type="file" accept=".txt,.json,.png,.pdf" (change)="attach($event)" [disabled]="busy"></label>}@for(e of history?.evidence || [];track e.id){<div class="evidence-item"><a [href]="'/api/evidence/'+e.id">{{e.name}}</a><small>SHA256 {{e.sha256}}</small></div>}
 @if(user.role==='administrador' && selected.status==='propuesto'){<label>Resultado de revisión<textarea rows="3" [(ngModel)]="reviewNote" placeholder="Describa qué evidencia verificó y sus límites…"></textarea></label><button class="primary" (click)="review()" [disabled]="busy || reviewNote.length<10">Registrar cierre revisado</button>}
 <h3>Historial inalterado</h3>@for(r of history?.revisions || [];track r.id){<div class="revision"><b>Revisión {{r.id}} · {{r.calculation.display_score}}</b><small>{{date(r.created_at)}} · {{r.policy_version}}</small><small>EPSS {{ctiStatus(r.snapshot.epss.status)}} · KEV {{ctiStatus(r.snapshot.kev.status)}}</small></div>}</aside>}
}
`})(PrimeApp);
bootstrapApplication(PrimeApp,{providers:[provideZonelessChangeDetection()]}).catch(err=>{document.body.textContent='No se pudo iniciar PRIME. '+String(err);});
